### ISSUE TITLE
Error: The intl string context variable "localizedCurrency" was not provided to the string "Yellow (+{cost}{localizedCurrency})"

### ISSUE THREAD

**Issue by antman94** [olegnn/react-shopping-cart#13]
Getting the same problem as in an old issue posted here: https://github.com/olegnn/react-shopping-cart/issues/5.

Is this still a known issue?

**Comment by olegnn** [comment]
Hello, which version of `intl-messageformat` do you use in your project?

You can use following command to determine:

```shell
npm list | grep intl-messageformat
```

**Comment by antman94** [comment]
Seems to be 9.1.5, I installed it with 'npm i intl-messageformat'. 

![ver](https://user-images.githubusercontent.com/13006925/87952396-12fc5800-caaa-11ea-9d45-ed971987cf41.PNG)

**Comment by antman94** [comment]
Which version was used in the example?

**Comment by olegnn** [comment]
8.4.0

I will investigate this issue in the next couple of days.

**Comment by olegnn** [comment]
Sorry for delay, fixed in https://github.com/olegnn/react-shopping-cart/commit/f5da3810c0c103efc462bc5b4ce8209de98a3f89
