### ISSUE TITLE
ReferenceError: window is not defined when used with Nextjs

### ISSUE THREAD

**Issue by stevenhart** [olegnn/react-shopping-cart#14]
I'm using Nextjs in my project, which causes the _window_ reference in **react-shopping-cart/dist/index.js** to error out since _window_ is not available.  **react-shopping-cart/dist/index.js** is minified so it's been difficult to try and deal with myself, do you have any advice for getting this to work?

I'm using the template code exactly from the README so besides this issue everything else seems to be in working order.  Thanks in advance!

<img width="1008" alt="Screen Shot 2021-02-04 at 5 19 26 PM" src="https://user-images.githubusercontent.com/8699535/106976380-2355e680-670d-11eb-9559-b5bef1d6976f.png">

**Comment by olegnn** [comment]
I think the problem is the same as [here](https://stackoverflow.com/questions/55849240/window-is-not-defined-after-a-build-with-webpack)
