### ISSUE TITLE
Error: The intl string context variable 'localizedCurrency' was not provided to the string 'Yellow (+{cost}{localizedCurrency})'

### ISSUE THREAD

**Issue by JSchatral** [olegnn/react-shopping-cart#5]
Hello,
I've created a create-react-app and  according to the readme file I add the  react-shopping-cart with yarn - nothing else. After that I implemented the example code with Redux and without Redux in the App.js file.
In runtime mode I get in both cases the same runtime Error: The intl string context variable 'localizedCurrency' was not provided to the string 'Yellow (+{cost}{localizedCurrency})'

I guess that this error should have something to do with "Localization"? According to the readme.md file I've do anything and should get the default language. 

Do I have something misunderstood? Have I overlooked something?
Thank you - Greeting from Germany...
J. Schatral

**Comment by olegnn** [comment]
It's been caused by updates in intl-messageformat package. In the last master version I've set strict version of all packages and now it seems to be working.
